version: 2
jobs:
  test_classification_model: 
    working_directory: ~/project/packages/classification_model
    docker:
      - image: circleci/python:3.8
    steps:
        - checkout:
          path: ~/project
        - run:
            name: Running tests
            command: |
              sudo pip install --upgrade pip
              pip install --user tox
              tox -e py38

workflows:
  version: 2
  test-all:
    jobs:
      - test_classification_model




